### ISSUE TITLE
Outputting MARC markup (.mrk)

### ISSUE THREAD

**Issue by ja573** [blackbeam/rust-marc#10]
Is there any way to output MARC markup using this crate?

**Comment by blackbeam** [comment]
Hi. What is MARC markup?

If you want to create a new MARC record or to edit an existing one please use [RecordBuilder](https://docs.rs/marc/latest/marc/struct.RecordBuilder.html).
[RecordBuilder::get_record](https://docs.rs/marc/latest/marc/struct.RecordBuilder.html#method.get_record) will return you an updated record that is actually a sequence of bytes, that you can write to a file or send over a network.

**Comment by ja573** [comment]
Hi @blackbeam ,

MARC21 markup It's the _human readable_ version of MARC21 records, which looks like:

```
=LDR  04974nam a2200541 i 4500
=001  xb32967639\
=006  m\\\\\\\\d\\\\\\\\
=007  cr\\n\\\\\\\\\
=008  221018t20222022enka\\\\sb\\\\001\0\eng\d
=020  \\$z9781800647503 (Hardback)
=020  \\$z9781800647497 (Paperback)
[...]
```

 `get_record()` gives you the standard, serialised, MARC21, that could be stored in a `.mrc` file. So I was wondering if it was at all possible to also output the markup version (`.mrk`)

**Comment by blackbeam** [comment]
Oh, I see. No, the library does not have this feature, sorry.
Is there a precise description of this format?

**Comment by ja573** [comment]
> Oh, I see. No, the library does not have this feature, sorry. Is there a precise description of this format?

I haven't been able to find a proper specification, but it's really just a plain-text (sort of) human-readable version of the record. It follows the following structure: `={field_number}  {indicators}{subfields}`; ordered by field number

**Comment by ja573** [comment]
Thanks a lot, @blackbeam , I've got something working off your snippet. It's be great being able to call this directly from `Record`. Are you accepting PRs? If so, to me it'd make sense to replace the current implementation of `fmt::Display`, what do you think?

**Comment by blackbeam** [comment]
> Are you accepting PRs?

Sure.
