### ISSUE TITLE
Writing records to a file

### ISSUE THREAD

**Issue by lannonbr** [blackbeam/rust-marc#2]
I am currently using your library for our library's MARC records, but we are interested in implementing the ability to write back out to a .mrc file so we can quickly manage our collection of records. A coworker and I are planning on implementing this. Would there be any suggestions on how you would want to implement it, or just go ahead with it?

**Comment by blackbeam** [comment]
Hi, Benjamin.

Maybe something like `Write` trait extension with ability to write records? Like [this one](http://burntsushi.net/rustdoc/byteorder/trait.WriteBytesExt.html) for example.

**Comment by lannonbr** [comment]
I believe this task is done. Closing
