### ISSUE TITLE
Get indicator about a Tag

### ISSUE THREAD

**Issue by universon123** [blackbeam/rust-marc#8]
Hey Anatoly:
in lib.rs file,about this test at sholud_build_record(),for example：                    
 "100", "1 ", [
                        'a' => "'Абд Ал-'Азиз Джа'фар Бин 'Акид",
                    ],
i dont't know how to get "1 " above;
please help me!
thank you!

**Comment by blackbeam** [comment]
Hi. You can get it by looking at the first two bytes of a data field data:

```rust
let indicator = some_data_field
    .get_data::<[u8]>()
    .get(..2)
    .map(Indicator::from_slice);
```
